# Generated by Django 5.2.8 on 2025-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedUser',
            fields=[
                ('login', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
    ]
